### ISSUE TITLE
Detect non-BIDS folder structures early and abort

### ISSUE THREAD

**Issue by nx10** [childmindresearch/bids2table#30]
We had an occurence where someone pointed b2t at a CPAC output directory also containing the CPAC/Nipype working dir (massive amount of tiny files) and b2t hung for a long time.

Could b2t somehow detect non-BIDS-conform folder structures early and abort the file scan?

**Comment by clane9** [comment]
I think this is a good issue to tackle next. @e-kenneally is looking into it.

**Comment by clane9** [comment]
Closed by #35.
