### ISSUE TITLE
Investigate os.scandir for initial file crawling

### ISSUE THREAD

**Issue by nx10** [childmindresearch/bids2table#32]
os.scandir is a fast directory iterator that avoids stat() syscalls

https://peps.python.org/pep-0471/

b2t currently uses iglob

https://github.com/childmindresearch/bids2table/blob/c3f4c12d97eb7bfb8f18da8ce4150ec3a2348493/bids2table/extractors/bids.py#L45

Not sure what performance improvements are realistic to see here, but this random benchmark shows >10x, so it might be worth investigating

https://dev.to/guionardo/fast-folder-iteration-in-python-3g1f

**Comment by clane9** [comment]
Thanks for the pointer. I looked into it and it seems iglob [uses scandir](https://github.com/python/cpython/blob/a8bcf3ec3284f042dab9cad676951092fb1f9890/Lib/glob.py#L169) under the hood. I also did a quick test comparing recursive scandir (as in the blog) with glob and they performed roughly similar. Closing for now but we may revisit this in the future.
